
# Server
HOST=0.0.0.0
PORT=1337

# Secrets
APP_KEYS=8K4yOAXiSb/58Ujsyr4hzA==,8FKutDlGblBF0FEktVWD+w==,hTIx4TnzLldGpos24vKgGg==,p88yzHrf+cwOmLWa71HPbw==
API_TOKEN_SALT=BVG9U9YSnZ2fNAea6b3niA==
ADMIN_JWT_SECRET=zoITNW8c6R471Lvi17eNRA==
TRANSFER_TOKEN_SALT=0XT++NQrkXO3Nx1Kk+Jgew==
ENCRYPTION_KEY=SiPBILc19kg+OadaNEwJSA==

# Database
DATABASE_CLIENT=postgres
DATABASE_HOST=aws-0-us-east-1.pooler.supabase.com
DATABASE_PORT=6543
DATABASE_NAME=postgres
DATABASE_USERNAME=postgres.qnceycokzbofzkmyxrzr
DATABASE_PASSWORD=P8oV0KMsRT9XlQ2s
DATABASE_SSL=false
DATABASE_FILENAME=
JWT_SECRET=aGzF7IlcIAIms6KKtF+DgA==


# R2
CF_ACCESS_KEY_ID=e91694181b1b59ae0f007647182797c9
CF_ACCESS_SECRET=be4e915c18d8bf276b926f4c708bdd1e3247ed117b56d96613ba7d652e334355
CF_ENDPOINT=https://6631e42f289efcec90f7973c87737e46.r2.cloudflarestorage.com
CF_BUCKET=chinasilktravel
CF_PUBLIC_ACCESS_URL=https://img.xiaoxisc.com